chore: make sure to init the service first

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -137,6 +137,8 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }}
 
       - name: Configure AWS Credentials
         id: creds
@@ -190,12 +192,25 @@ jobs:
             echo "Environment already exists."
           fi
 
+      - name: Setup Git Config
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Commit copilot configs
+        run: |
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
+
   build-and-deploy:
     needs: [test, create-copilot-environment]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }}
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
@@ -263,7 +278,33 @@ jobs:
           # Optional: Clean up the temporary directory
           rm -rf ${{ runner.temp }}/copilot-download
 
-      - name: Deploy to AWS using Copilot
+      - name: Deploy App to AWS using Copilot
         run: |
           export IMAGE_LOCATION="${{ steps.generate_ghcr_tag.outputs.image }}"
-          copilot svc deploy --name nextjs-app --env ${{ github.head_ref }}
+          # Check if the service exists
+          if ! copilot svc show --name nextjs-app --json; then
+            echo "Service does not exist, initializing..."
+            # Initialize service if it doesn't exist
+            if ! copilot svc init --app ocean-watch --name nextjs-app --svc-type "Load Balanced Web Service"; then
+              echo "Failed to initialize service."
+              exit 1
+            fi
+            # Deploy the new service
+            if ! copilot svc deploy --name nextjs-app --env ${{ github.head_ref }}; then
+              echo "Failed to deploy service."
+              exit 1
+            fi
+          else
+            echo "Service already exists."
+          fi
+
+      - name: Setup Git Config
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Commit copilot configs
+        run: |
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
