chore: add job to init the copilot app

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -11,7 +11,7 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
@@ -66,12 +66,77 @@ jobs:
       - name: No-op Test Placeholder
         run: echo "No tests implemented yet"
 
+  init-copilot:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Ensure you fetch all history for all branches and tags
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+
+      - name: DEBUG - Test AWS CLI with assumed role
+        run: |
+          aws sts get-caller-identity
+
+      - name: Install AWS Copilot
+        run: |
+          # Create a temporary directory for downloading
+          mkdir -p ${{ runner.temp }}/copilot-download
+
+          # Download the Copilot binary to the temporary directory
+          curl -Lo ${{ runner.temp }}/copilot-download/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
+
+          # Make the binary executable
+          chmod +x ${{ runner.temp }}/copilot-download/copilot
+
+          # Move the Copilot binary to a directory in PATH
+          sudo mv ${{ runner.temp }}/copilot-download/copilot /usr/local/bin/copilot
+
+          # Optional: Clean up the temporary directory
+          rm -rf ${{ runner.temp }}/copilot-download
+
+      - name: Check for existing Copilot application
+        id: check_app
+        run: |
+          if copilot app ls | grep -qw "ocean-watch"; then
+            echo "App exists."
+            echo "app_exists=true" >> $GITHUB_ENV
+          else
+            echo "App does not exist."
+            echo "app_exists=false" >> $GITHUB_ENV
+          fi
+
+      - name: Initialize Copilot application
+        if: env.app_exists == 'false'
+        run: copilot app init ocean-watch # Add other initialization parameters as needed
+
+      - name: Setup Git Config
+        if: env.app_exists == 'false'
+        run: |
+          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+
+      - name: Commit copilot configs
+        if: env.app_exists == 'false'
+        run: |
+          git add copilot/*
+          git commit -m "AWS copilot configs generated by GitHub Actions Bot" -a || echo "No changes to commit"
+          git push
+
   build-and-deploy:
-    needs: test
+    needs: [test, init-copilot]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
