refactor: break out the `deploy` job

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -310,35 +310,42 @@ jobs:
           # Store the ARN for use in subsequent steps
           echo "SECRET_ARN=$SECRET_ARN" >> $GITHUB_ENV
 
+      - name: Check for existing Copilot service deployment
+        id: check_service_deployment
+        run: |
+          if copilot svc show --name nextjs-app --json; then
+            echo "Service exists."
+            echo "service_exists=true" >> $GITHUB_ENV
+          else
+            echo "Service does not exist."
+            echo "service_exists=false" >> $GITHUB_ENV
+          fi
+
+      - name: Initialize Service
+        id: init-service
+        if: env.service_exists == 'false'
+        run: |
+          export IMAGE_LOCATION="${{ needs.build-image.outputs.imageURL }}"
+          export GHCR_ACCESS="${{ env.SECRET_ARN }}"
+          if ! copilot svc init --app ocean-watch --name nextjs-app --svc-type "Load Balanced Web Service"; then
+            echo "Failed to initialize service."
+            exit 1
+          fi
+
       - name: Deploy App to AWS using Copilot
         run: |
           export IMAGE_LOCATION="${{ needs.build-image.outputs.imageURL }}"
           export GHCR_ACCESS="${{ env.SECRET_ARN }}"
-          # Check if the service exists
-          if ! copilot svc show --name nextjs-app --json; then
-            echo "Service does not exist, initializing..."
-            # Initialize service if it doesn't exist
-            if ! copilot svc init --app ocean-watch --name nextjs-app --svc-type "Load Balanced Web Service"; then
-              echo "Failed to initialize service."
-              exit 1
-            fi
-          else
-            echo "Service already exists."
-          fi
-          # Deploy the new service
           if ! copilot svc deploy --force --name nextjs-app --env ${{ github.head_ref }}; then
             echo "Failed to deploy service."
             copilot svc delete --name nextjs-app --env ${{ github.head_ref }} --yes
             exit 1
           fi
-          SERVICE_INFO=$(copilot svc show --app ocean-watch --name nextjs-app --json)
-          echo "$SERVICE_INFO" | jq .
-          copilot svc status --app ocean-watch --env ${{ github.head_ref }} --name nextjs-app --json
 
       - name: Show Service Information
         id: service_info
         run: |
-          ENV_NAME="${{ github.head_ref }}" # Capture the GitHub head reference
+          ENV_NAME="${{ github.head_ref }}"
           SERVICE_JSON=$(copilot svc show --app ocean-watch --name nextjs-app --json)
           SERVICE_URL=$(echo "$SERVICE_JSON" | jq -r --arg ENV_NAME "$ENV_NAME" '.routes[] | select(.environment == $ENV_NAME) | .url')
           
@@ -360,13 +367,10 @@ jobs:
             🚀 Deployment successful!
             🌐 Your service in environment `${{ github.head_ref }}` is now available at: ${{ steps.service_info.outputs.url }}
 
-      - name: Setup Git Config
+      - name: Commit Copilot Service Configs
         run: |
           git config --global user.email "action@github.com"
           git config --global user.name "GitHub Action"
-
-      - name: Commit copilot configs
-        run: |
           git add -A  # Adds all changes, including untracked files
           git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
           git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
