Chore: Update Dockerfile and Create Review App Workflows (#9)
* chore: update Dockerfile

* chore: deploy review app based on git branch

* chore: only build one arch to speed things up

* chore: make sure to ask for a shorter duration than the role is allowed

* chore: download and install AWS copilot CLI

* chore: add debugging for AWS credentials

* chore: update aws credentials

* chore: over-specifying the AWS credentials

* chore: set image location in copilot manifest.yml

* chore: add job to init the copilot app

* chore: if the init fails, delete the app

* chore: do not `delete` app

* chore: tweak git commands

* AWS copilot configs generated by GitHub Actions Bot

* chore: split out the creating of the copilot environment

* chore: better environment checking

* chore: debugging copilot env show

* chore: copilot create env

* chore: remove explicit profile

* chore: use default environment

* chore: add permissions boundary to copilot init

* chore: explicitly set the session token

* chore: cat out the manifest.yml

* chore: try permissions boundary again

* chore: copilot environment permissions are separate from application permissions

* chore: permissions boundary didn't pan out

* chore: make sure to init the service first

* chore: add resource tags

* AWS copilot configs generated by GitHub Actions Bot

* chore: add service port

* chore: add credentials parameter for ghcr

* chore: add step to create AWS access to ghcr.

Because each secret used my copilot needs an environment tag, I don't think I can use
just one secret to control all access.

Therefore, I'm checking for and adding a secret
with the correct information for each environment.

* fix: typo in tag creation for AWS secret

* chore: re-enable the docker build/push steps

* chore: force a new deployment even if the previous isn't finished

We always want the latest changes to be on the environment. So, scrap what you're working on and
redeploy.

* chore: try to delete the service if it fails deployment

* chore: add a description to the secret creation

* chore: add status of the service after successful deployment

* chore: show service info after a successful deploy

* chore: update checkout action version and shorten Docker image sha

* fix: `manifest` cannot be specified if other flags are used

* fix: use bash to shorten SHA

* fix: use the PR branch's latest sha

* chore: add the URL to the PR comments for dev convenience

* refactor: update github actions versions

* refactor: only download copilot cli once

Save it to artifacts for other jobs.

* refactor: remove debug output

* refactor: build docker image in its own job

* fix: update upload-artifact version

* chore: update docker github action versions

* chore: update pr update-comment github action version

* chore: refactor `create-copilot-environment`

* refactor: break out the `deploy` job

* refactor: update ::set-output directive

* chore: change the Docker image name and tag

Removed the `latest` tag for images built in a feature branch

* chore: add workflow for merging in branches to main

---------

Co-authored-by: GitHub Action <action@github.com>

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -11,15 +11,15 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v4
         with:
           node-version: '14.17'
 
       - name: Cache Node Modules
-        uses: actions/cache@v2
+        uses: actions/cache@v4
         env:
           cache-name: cache-node-modules
         with:
@@ -43,15 +43,15 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v4
         with:
           node-version: '14.17'
 
       - name: Cache Node Modules
-        uses: actions/cache@v2
+        uses: actions/cache@v4
         env:
           cache-name: cache-node-modules
         with:
@@ -66,21 +66,25 @@ jobs:
       - name: No-op Test Placeholder
         run: echo "No tests implemented yet"
 
-  build-and-deploy:
-    needs: test
+  build-image:
+    needs: [ test ]
     runs-on: ubuntu-latest
+    outputs:
+      imageURL: ${{ steps.generate_ghcr_tag.outputs.image }}
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
 
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
+        uses: docker/setup-qemu-action@v3
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
 
       - name: Log in to GitHub Container Registry
-        uses: docker/login-action@v1
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
@@ -88,33 +92,284 @@ jobs:
 
       - name: generate ghcr tag
         id: generate_ghcr_tag
-        run: echo "::set-output name=image::ghcr.io/${{ github.repository }}/${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}:${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
+        run: |
+          SHORT_SHA=${{ github.event.pull_request.head.sha }}
+          SHORT_SHA=${SHORT_SHA:0:7}  # Using Bash substring extraction
+          echo "image=ghcr.io/${{ github.repository }}/nextjs-app:${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}-$SHORT_SHA" >> $GITHUB_OUTPUT
 
       - name: Build and Push Docker Image
-        uses: docker/build-push-action@v2
+        uses: docker/build-push-action@v5
         with:
-          platforms: linux/amd64,linux/arm64/v8
+          platforms: linux/amd64
           context: .
           file: ./Dockerfile
           push: true
           tags: |
             ${{ steps.generate_ghcr_tag.outputs.image }}
-            ghcr.io/${{ github.repository }}/${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}:latest
 
       - name: Comment PR with GHCR details
-        uses: peter-evans/create-or-update-comment@v1
+        uses: peter-evans/create-or-update-comment@v4
         with:
           issue-number: ${{ github.event.pull_request.number }}
           body: |
             📦 New Docker Image has been pushed to Github Container Registry (GHCR)
             Image: ${{ steps.generate_ghcr_tag.outputs.image }}
 
-
-      - name: Deploy to AWS using Copilot
-        if: false # This condition effectively disables the step until copilot is set up
+  setup-copilot:
+    runs-on: ubuntu-latest
+    outputs:
+      copilot-path: ${{ steps.setup.outputs.copilot-path }}
+    steps:
+      - name: Create a temporary directory for downloading
+        id: setup
         run: |
-          copilot svc deploy --name your-service-name --env your-environment-name
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: your-aws-region # e.g., us-east-1
+          mkdir -p ${{ runner.temp }}/copilot-download
+          echo "copilot-path=${{ runner.temp }}/copilot-download/copilot" >> $GITHUB_OUTPUT
+      - name: Download Copilot CLI
+        run: |
+          curl -Lo ${{ steps.setup.outputs.copilot-path }} https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
+      - name: Make binary executable
+        run: chmod +x ${{ steps.setup.outputs.copilot-path }}
+      - name: Upload Copilot CLI to Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: copilot-cli
+          path: ${{ steps.setup.outputs.copilot-path }}
+
+  init-copilot:
+    runs-on: ubuntu-latest
+    needs: setup-copilot
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
+
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Check for existing Copilot application
+        id: check_app
+        run: |
+          if copilot app ls | grep -qw "ocean-watch"; then
+            echo "App exists."
+            echo "app_exists=true" >> $GITHUB_ENV
+          else
+            echo "App does not exist."
+            echo "app_exists=false" >> $GITHUB_ENV
+          fi
+
+      - name: Initialize Copilot application
+        if: env.app_exists == 'false'
+        run: copilot app init ocean-watch --resource-tags program=Oceans,project=OceanWatch,application=OceanWatch
+
+      - name: Setup Git Config
+        if: env.app_exists == 'false'
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Commit copilot configs
+        if: env.app_exists == 'false'
+        run: |
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
+
+  create-copilot-environment:
+    needs: [init-copilot]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
+
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
+
+      - name: Configure AWS Credentials
+        id: creds
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+          output-credentials: true
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Check for existing Copilot environment
+        id: check_environment
+        run: |
+          if copilot env show --name ${{ github.head_ref }} --json; then
+            echo "Environment exists."
+            echo "environment_exists=true" >> $GITHUB_ENV
+          else
+            echo "Environment does not exist."
+            echo "environment_exists=false" >> $GITHUB_ENV
+          fi
+
+      - name: Initialize Environment
+        id: init-environment
+        if: env.environment_exists == 'false'
+        run: |
+          if ! copilot env init --name ${{ github.head_ref }} --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
+            echo "Failed to initialize environment."
+            exit 1
+          fi
+
+      - name: Deploy Environment
+        run: |
+          if ! copilot env deploy --name ${{ github.head_ref }} --app ocean-watch; then
+            echo "Failed to deploy environment."
+            exit 1
+          fi
+
+      - name: Commit copilot environment configs
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot environment configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
+
+  deploy:
+    needs: [build-image, create-copilot-environment]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
+
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Handle AWS Secret --> GHCR Access
+        run: |
+          # Install jq if it's not available
+          sudo apt-get update && sudo apt-get install -y jq
+          
+          SECRET_NAME="ocean-watch-env-${{ github.head_ref }}"
+          SECRET_VALUE='{"username":"${{ secrets.AWS_GHCR_ACCESS_TOKEN }}","password":"${{ secrets.AWS_GHCR_ACCESS_TOKEN }}"}'
+          TAGS='Key=project,Value=OceanWatch Key=program,Value=Oceans Key=application,Value=OceanWatch Key=copilot-application,Value=ocean-watch Key=copilot-environment,Value=${{ github.head_ref }}'
+          DESCRIPTION='Read-only access to github container registry'
+          
+          # Check if the AWS Secret already exists
+          SECRET_INFO=$(aws secretsmanager describe-secret --secret-id $SECRET_NAME || echo "not_found")
+          
+          if [[ "$SECRET_INFO" == "not_found" ]]; then
+            echo "Secret does not exist, creating..."
+            # Create the secret and extract the ARN
+            SECRET_OUTPUT=$(aws secretsmanager create-secret --name $SECRET_NAME --secret-string "$SECRET_VALUE" --tags $TAGS --description $DESCRIPTION)
+            SECRET_ARN=$(echo $SECRET_OUTPUT | jq -r .ARN)
+            echo "Secret created with ARN: $SECRET_ARN"
+          else
+            echo "Secret already exists."
+            # Extract the ARN from existing secret info
+            SECRET_ARN=$(echo $SECRET_INFO | jq -r .ARN)
+          fi
+
+          # Store the ARN for use in subsequent steps
+          echo "SECRET_ARN=$SECRET_ARN" >> $GITHUB_ENV
+
+      - name: Check for existing Copilot service deployment
+        id: check_service_deployment
+        run: |
+          if copilot svc show --name nextjs-app --json; then
+            echo "Service exists."
+            echo "service_exists=true" >> $GITHUB_ENV
+          else
+            echo "Service does not exist."
+            echo "service_exists=false" >> $GITHUB_ENV
+          fi
+
+      - name: Initialize Service
+        id: init-service
+        if: env.service_exists == 'false'
+        run: |
+          export IMAGE_LOCATION="${{ needs.build-image.outputs.imageURL }}"
+          export GHCR_ACCESS="${{ env.SECRET_ARN }}"
+          if ! copilot svc init --app ocean-watch --name nextjs-app --svc-type "Load Balanced Web Service"; then
+            echo "Failed to initialize service."
+            exit 1
+          fi
+
+      - name: Deploy App to AWS using Copilot
+        run: |
+          export IMAGE_LOCATION="${{ needs.build-image.outputs.imageURL }}"
+          export GHCR_ACCESS="${{ env.SECRET_ARN }}"
+          if ! copilot svc deploy --force --name nextjs-app --env ${{ github.head_ref }}; then
+            echo "Failed to deploy service."
+            copilot svc delete --name nextjs-app --env ${{ github.head_ref }} --yes
+            exit 1
+          fi
+
+      - name: Show Service Information
+        id: service_info
+        run: |
+          ENV_NAME="${{ github.head_ref }}"
+          SERVICE_JSON=$(copilot svc show --app ocean-watch --name nextjs-app --json)
+          SERVICE_URL=$(echo "$SERVICE_JSON" | jq -r --arg ENV_NAME "$ENV_NAME" '.routes[] | select(.environment == $ENV_NAME) | .url')
+          
+          if [[ -z "$SERVICE_URL" || "$SERVICE_URL" == "null" ]]; then
+            echo "No URL found for the specified environment: $ENV_NAME"
+            echo "$SERVICE_JSON"
+            exit 1
+          fi
+          
+          echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT
+          echo "Service URL: $SERVICE_URL"
+
+      - name: Comment PR with Service URL
+        if: github.event_name == 'pull_request'
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            🚀 Deployment successful!
+            🌐 Your service in environment `${{ github.head_ref }}` is now available at: ${{ steps.service_info.outputs.url }}
+
+      - name: Commit Copilot Service Configs
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
