chore: add service port

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -289,13 +289,13 @@ jobs:
               echo "Failed to initialize service."
               exit 1
             fi
-            # Deploy the new service
-            if ! copilot svc deploy --name nextjs-app --env ${{ github.head_ref }}; then
-              echo "Failed to deploy service."
-              exit 1
-            fi
           else
             echo "Service already exists."
+          fi
+          # Deploy the new service
+          if ! copilot svc deploy --name nextjs-app --env ${{ github.head_ref }}; then
+            echo "Failed to deploy service."
+            exit 1
           fi
 
       - name: Setup Git Config
