chore: refactor `create-copilot-environment`

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -220,35 +220,39 @@ jobs:
         with:
           ref: ${{ github.head_ref }}
 
-      - name: Check and Create Environment
+      - name: Check for existing Copilot environment
+        id: check_environment
         run: |
-          # Check if the environment exists
-          if ! copilot env show --name ${{ github.head_ref }} --json; then
-            echo "Environment does not exist, initializing..."
-            # Initialize environment if it doesn't exist
-            if ! copilot env init --name ${{ github.head_ref }} --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
-              echo "Failed to initialize environment."
-              cat copilot/environments/deployment-review-apps/manifest.yml
-              exit 1
-            fi
-            # Deploy the new environment
-            if ! copilot env deploy --name ${{ github.head_ref }} --app ocean-watch; then
-              echo "Failed to deploy environment."
-              exit 1
-            fi
+          if copilot env show --name ${{ github.head_ref }} --json; then
+            echo "Environment exists."
+            echo "environment_exists=true" >> $GITHUB_ENV
           else
-            echo "Environment already exists."
+            echo "Environment does not exist."
+            echo "environment_exists=false" >> $GITHUB_ENV
           fi
 
-      - name: Setup Git Config
+      - name: Initialize Environment
+        id: init-environment
+        if: env.environment_exists == 'false'
+        run: |
+          if ! copilot env init --name ${{ github.head_ref }} --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
+            echo "Failed to initialize environment."
+            exit 1
+          fi
+
+      - name: Deploy Environment
+        run: |
+          if ! copilot env deploy --name ${{ github.head_ref }} --app ocean-watch; then
+            echo "Failed to deploy environment."
+            exit 1
+          fi
+
+      - name: Commit copilot environment configs
         run: |
           git config --global user.email "action@github.com"
           git config --global user.name "GitHub Action"
-
-      - name: Commit copilot configs
-        run: |
           git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git diff-index --quiet HEAD || git commit -m "AWS copilot environment configs generated by GitHub Actions Bot"
           git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
 
   deploy:
