refactor: build docker image in its own job

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -66,154 +66,12 @@ jobs:
       - name: No-op Test Placeholder
         run: echo "No tests implemented yet"
 
-  setup-copilot:
+  build-image:
+    needs: [ test ]
     runs-on: ubuntu-latest
     outputs:
-      copilot-path: ${{ steps.setup.outputs.copilot-path }}
+      imageURL: ${{ steps.generate_ghcr_tag.outputs.image }}
     steps:
-      - name: Create a temporary directory for downloading
-        id: setup
-        run: |
-          mkdir -p ${{ runner.temp }}/copilot-download
-          echo "::set-output name=copilot-path::${{ runner.temp }}/copilot-download/copilot"
-      - name: Download Copilot CLI
-        run: |
-          curl -Lo ${{ steps.setup.outputs.copilot-path }} https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
-      - name: Make binary executable
-        run: chmod +x ${{ steps.setup.outputs.copilot-path }}
-      - name: Upload Copilot CLI to Artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: copilot-cli
-          path: ${{ steps.setup.outputs.copilot-path }}
-
-  init-copilot:
-    runs-on: ubuntu-latest
-    needs: setup-copilot
-    steps:
-      - name: Download Copilot CLI from Artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: copilot-cli
-          path: /usr/local/bin
-
-      - name: Ensure Copilot is executable
-        run: chmod +x /usr/local/bin/copilot
-
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
-          role-duration-seconds: 1800
-
-      - name: Check for existing Copilot application
-        id: check_app
-        run: |
-          if copilot app ls | grep -qw "ocean-watch"; then
-            echo "App exists."
-            echo "app_exists=true" >> $GITHUB_ENV
-          else
-            echo "App does not exist."
-            echo "app_exists=false" >> $GITHUB_ENV
-          fi
-
-      - name: Initialize Copilot application
-        if: env.app_exists == 'false'
-        run: copilot app init ocean-watch --resource-tags program=Oceans,project=OceanWatch,application=OceanWatch
-
-      - name: Setup Git Config
-        if: env.app_exists == 'false'
-        run: |
-          git config --global user.email "action@github.com"
-          git config --global user.name "GitHub Action"
-
-      - name: Commit copilot configs
-        if: env.app_exists == 'false'
-        run: |
-          git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
-          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
-
-  create-copilot-environment:
-    needs: [init-copilot]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download Copilot CLI from Artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: copilot-cli
-          path: /usr/local/bin
-
-      - name: Ensure Copilot is executable
-        run: chmod +x /usr/local/bin/copilot
-
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
-
-      - name: Configure AWS Credentials
-        id: creds
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
-          role-duration-seconds: 1800
-          output-credentials: true
-
-      - name: Check and Create Environment
-        run: |
-          # Check if the environment exists
-          if ! copilot env show --name ${{ github.head_ref }} --json; then
-            echo "Environment does not exist, initializing..."
-            # Initialize environment if it doesn't exist
-            if ! copilot env init --name ${{ github.head_ref }} --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
-              echo "Failed to initialize environment."
-              cat copilot/environments/deployment-review-apps/manifest.yml
-              exit 1
-            fi
-            # Deploy the new environment
-            if ! copilot env deploy --name ${{ github.head_ref }} --app ocean-watch; then
-              echo "Failed to deploy environment."
-              exit 1
-            fi
-          else
-            echo "Environment already exists."
-          fi
-
-      - name: Setup Git Config
-        run: |
-          git config --global user.email "action@github.com"
-          git config --global user.name "GitHub Action"
-
-      - name: Commit copilot configs
-        run: |
-          git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
-          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
-
-  build-and-deploy:
-    needs: [test, create-copilot-environment]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download Copilot CLI from Artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: copilot-cli
-          path: /usr/local/bin
-
-      - name: Ensure Copilot is executable
-        run: chmod +x /usr/local/bin/copilot
-
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
@@ -258,6 +116,40 @@ jobs:
             📦 New Docker Image has been pushed to Github Container Registry (GHCR)
             Image: ${{ steps.generate_ghcr_tag.outputs.image }}
 
+  setup-copilot:
+    runs-on: ubuntu-latest
+    outputs:
+      copilot-path: ${{ steps.setup.outputs.copilot-path }}
+    steps:
+      - name: Create a temporary directory for downloading
+        id: setup
+        run: |
+          mkdir -p ${{ runner.temp }}/copilot-download
+          echo "::set-output name=copilot-path::${{ runner.temp }}/copilot-download/copilot"
+      - name: Download Copilot CLI
+        run: |
+          curl -Lo ${{ steps.setup.outputs.copilot-path }} https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
+      - name: Make binary executable
+        run: chmod +x ${{ steps.setup.outputs.copilot-path }}
+      - name: Upload Copilot CLI to Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: copilot-cli
+          path: ${{ steps.setup.outputs.copilot-path }}
+
+  init-copilot:
+    runs-on: ubuntu-latest
+    needs: setup-copilot
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
+
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -266,6 +158,125 @@ jobs:
           aws-region: ${{ secrets.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
           role-duration-seconds: 1800
+
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Check for existing Copilot application
+        id: check_app
+        run: |
+          if copilot app ls | grep -qw "ocean-watch"; then
+            echo "App exists."
+            echo "app_exists=true" >> $GITHUB_ENV
+          else
+            echo "App does not exist."
+            echo "app_exists=false" >> $GITHUB_ENV
+          fi
+
+      - name: Initialize Copilot application
+        if: env.app_exists == 'false'
+        run: copilot app init ocean-watch --resource-tags program=Oceans,project=OceanWatch,application=OceanWatch
+
+      - name: Setup Git Config
+        if: env.app_exists == 'false'
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Commit copilot configs
+        if: env.app_exists == 'false'
+        run: |
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
+
+  create-copilot-environment:
+    needs: [init-copilot]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
+
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
+
+      - name: Configure AWS Credentials
+        id: creds
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+          output-credentials: true
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Check and Create Environment
+        run: |
+          # Check if the environment exists
+          if ! copilot env show --name ${{ github.head_ref }} --json; then
+            echo "Environment does not exist, initializing..."
+            # Initialize environment if it doesn't exist
+            if ! copilot env init --name ${{ github.head_ref }} --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
+              echo "Failed to initialize environment."
+              cat copilot/environments/deployment-review-apps/manifest.yml
+              exit 1
+            fi
+            # Deploy the new environment
+            if ! copilot env deploy --name ${{ github.head_ref }} --app ocean-watch; then
+              echo "Failed to deploy environment."
+              exit 1
+            fi
+          else
+            echo "Environment already exists."
+          fi
+
+      - name: Setup Git Config
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Commit copilot configs
+        run: |
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
+
+  deploy:
+    needs: [build-image, create-copilot-environment]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
+
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
 
       - name: Handle AWS Secret --> GHCR Access
         run: |
@@ -297,7 +308,7 @@ jobs:
 
       - name: Deploy App to AWS using Copilot
         run: |
-          export IMAGE_LOCATION="${{ steps.generate_ghcr_tag.outputs.image }}"
+          export IMAGE_LOCATION="${{ needs.build-image.outputs.imageURL }}"
           export GHCR_ACCESS="${{ env.SECRET_ARN }}"
           # Check if the service exists
           if ! copilot svc show --name nextjs-app --json; then
