chore: split out the creating of the copilot environment

diff --git a/.github/workflows/pr-commit-stage.yml b/.github/workflows/pr-commit-stage.yml
--- a/.github/workflows/pr-commit-stage.yml
+++ b/.github/workflows/pr-commit-stage.yml
@@ -131,8 +131,61 @@ jobs:
           git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
           git push origin HEAD:${{ github.head_ref }}  # Ensure you're pushing to the correct branch
 
+  create-copilot-environment:
+    needs: [init-copilot]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ocean-watch-deployer
+          role-duration-seconds: 1800
+
+      - name: DEBUG - Test AWS CLI with assumed role
+        run: |
+          aws sts get-caller-identity
+
+      - name: Install AWS Copilot
+        run: |
+          # Create a temporary directory for downloading
+          mkdir -p ${{ runner.temp }}/copilot-download
+
+          # Download the Copilot binary to the temporary directory
+          curl -Lo ${{ runner.temp }}/copilot-download/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
+
+          # Make the binary executable
+          chmod +x ${{ runner.temp }}/copilot-download/copilot
+
+          # Move the Copilot binary to a directory in PATH
+          sudo mv ${{ runner.temp }}/copilot-download/copilot /usr/local/bin/copilot
+
+          # Optional: Clean up the temporary directory
+          rm -rf ${{ runner.temp }}/copilot-download
+
+      - name: Check and Create Environment
+        run: |
+          if ! copilot env show --name ${{ github.head_ref }} --json | jq -e .name > /dev/null; then
+            echo "Environment does not exist, initializing..."
+            if ! copilot env init --name ${{ github.head_ref }} --profile default --app ocean-watch --region $AWS_REGION; then
+              echo "Failed to initialize environment."
+              exit 1
+            fi
+            if ! copilot env deploy --name ${{ github.head_ref }} --app ocean-watch; then
+              echo "Failed to deploy environment."
+              exit 1
+            fi
+          else
+            echo "Environment already exists."
+          fi
+
   build-and-deploy:
-    needs: [test, init-copilot]
+    needs: [test, create-copilot-environment]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
@@ -203,13 +256,6 @@ jobs:
 
           # Optional: Clean up the temporary directory
           rm -rf ${{ runner.temp }}/copilot-download
-
-      - name: Check and Create Environment
-        run: |
-          if ! copilot env show --name ${{ github.head_ref }} --json | jq -e .name; then
-            copilot env init --name ${{ github.head_ref }} --profile default --app ocean-watch --region ${{ secrets.AWS_REGION }}
-            copilot env deploy --name ${{ github.head_ref }} --app ocean-watch
-          fi
 
       - name: Deploy to AWS using Copilot
         run: |
